package nl.q42.core.contentful;

public enum CFCampaignEventColor
{
  NO_COLOR,
  CONTENT_ONE,
  CONTENT_TWO,
  CONTENT_THREE,
  CONTENT_FOUR,
  CONTENT_FIVE,
  CONTENT_SIX,
  CONTENT_SEVEN,
  CONTENT_EIGHT,
  CONTENT_NINE,
  CONTENT_TEN,
  CONTENT_SUBTLE_ONE,
  CONTENT_SUBTLE_TWO,
  CONTENT_SUBTLE_THREE,
  CONTENT_SUBTLE_FOUR,
  CONTENT_SUBTLE_FIVE,
  CONTENT_SUBTLE_SIX,
  CONTENT_SUBTLE_SEVEN,
  CONTENT_SUBTLE_EIGHT,
  CONTENT_STAPELGEK_ONE,
  CONTENT_STAPELGEK_TWO,
  CONTENT_HOLIDAYS_ONE,
  CONTENT_HOLIDAYS_TWO,
  CONTENT_HOLIDAYS_THREE,
  CONTENT_ACTIEALARM_ONE,
  CONTENT_ACTIEALARM_TWO,
  CONTENT_SALE_ONE,
  CONTENT_SALE_TWO
}
