package nl.q42.sdui.component.image;

public enum LocalImages
{
  ACCOUNT_FAVORITES, ACCOUNT_ORDERS, ACCOUNT_PROFILE, ACCOUNT_VOUCHERS, ADD_ROUNDED,
  ANDROID_NAVIGATION_NEXT, BASKET_ICON, CALCULATE_QUOTATION, CATEGORY, CHECKMARK, CHECKMARK_THIN,
  CIRCLE_PLUS, CLOCK, COLOR_WHEEL, COOKIES_ICON, COPY, CUSTOMER_SERVICE_CHAT,
  CUSTOMER_SERVICE_FB_MESSENGER, CUSTOMER_SERVICE_PHONE, CUSTOMER_SERVICE_TWITTER, DELETE,
  DOCUMENT_ICON, EDIT_CAKE, EDIT_CAKE_OUTLINED, ERROR, EXTERNAL_LINK, FILTER, FOLDER, GLOBE_ICON,
  HEMA_LOGO, HOME_CUSTOMER_SERVICE, HOME_EXTERNAL_LINK, HOME_RECALL, HOME_SCANNER,
  IMAGE_DELIVERY_CAR, IMAGE_DELIVERY_SHOP, LIGHT_BULB, LOCATION_ICON, NOT_AVAILABLE,
  NOTIFICATION_ICON, MAIL_ICON, PACKAGE, PAYMENT_OPTIONS, PROCESSING, PROMOTION, REMOVE, REVIEWS,
  SEARCH, SEARCH_SCANNER, SHARE, SIGN_OUT, SIZE, STORE, VOUCHER, BUSINESS, APPLE, INFO,
  HEMA_LOYALTY_NL, HEMA_LOYALTY_BE;

  public LocalImage toLocalImage()
  {
    return new LocalImage(this);
  }

  public LocalImage toLocalImage(String alt)
  {
    return new LocalImage(this, alt);
  }
}